name: .NET

on:
  push:
    branches: [ "master", "feature/b2c-auth" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:
    runs-on: ubuntu-22.04

    steps:
    - uses: actions/checkout@v3
    - name: Setup .NET
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: 6.0.x
    - name: Restore dependencies
      run: dotnet restore
    - name: Build
      run: dotnet build --no-restore --configuration Release
    - name: Test
      run: dotnet test --no-build --verbosity normal
    # TODO: specify project to avoid publishing extra projects
    - name: Publish
      run: dotnet publish --no-build --configuration Release
    - name: Upload publish folder
      uses: actions/upload-artifact@v3
      with:
        name: publish-folder
        path: ${{ github.workspace }}/CarpetPlanner/bin/Release/net6.0/publish/
        if-no-files-found: error

  deploy:
    name: "Deploy to production"
    runs-on: ubuntu-22.04
    #if: github.event_name == 'push' && github.ref == 'refs/heads/master'
    needs: build
    steps:
      - name: Configure SSH
        run: |
          mkdir -p ~/.ssh/
          echo "$SSH_KEY" > ~/.ssh/production.key
          chmod 600 ~/.ssh/production.key
          cat >>~/.ssh/config <<END
          Host production
            HostName $SSH_HOST
            User $SSH_USER
            IdentityFile ~/.ssh/production.key
            StrictHostKeyChecking no
          END
        env:
          SSH_USER: ${{ secrets.PRODUCTION_SSH_USER }}
          SSH_KEY: ${{ secrets.PRODUCTION_SSH_KEY }}
          SSH_HOST: ${{ secrets.PRODUCTION_SSH_HOST }}
      - name: Download publish artifact
        uses: actions/download-artifact@v3
        with:
          name: publish-folder
          path: ~/download/publish-folder
      #- name: Stop the server
      #  run: ssh production 'sudo systemctl stop kestrel-matto.service'
      - name: Copy publish folder contents to production server
        run: scp -r -F ~/.ssh/production.key /home/runner/download/publish-folder ${{ secrets.PRODUCTION_SSH_USER }}@${{ secrets.PRODUCTION_SSH_HOST }}:/var/www/carpetplanner.new
      #- name: Start the server
      #  if: ${{ always() }}
      #  run: ssh production 'sudo systemctl start kestrel-matto.service'
