name: Publish container image

on:
  push:
    branches: [ "master", "feature/psql" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:
    name: "Build image"
    runs-on: ubuntu-22.04

    steps:
    - name: Checkout
      uses: actions/checkout@v3
    - name: Login to container registry
      uses: docker/login-action@v3
      with:
        registry: ${{ secrets.CONTAINER_REGISTRY_ADDRESS }}
        username: ${{ secrets.CONTAINER_REGISTRY_USER }}
        password: ${{ secrets.CONTAINER_REGISTRY_PASSWORD }}
    - name: Build and push image
      uses: docker/build-push-action@v5
      with:
        file: CarpetPlanner/Dockerfile
        platforms: linux/arm64
        push: true
        tags: ${{ secrets.CONTAINER_REGISTRY_ADDRESS}}/carpetplanner:latest
