name: Publish container image

on:
  push:
    branches: [ "master", "feature/psql" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:
    name: "Build image"
    runs-on: ubuntu-22.04

    steps:
    - name: Checkout
      uses: actions/checkout@v3
    - name: Build image
      run: docker build -f ${{ github.workspace }}/CarpetPlanner/Dockerfile -t cr.pulkkinen.dev/carpetplanner:latest .
