name: Publish container image

on:
  push:
    branches: [ "master", "feature/psql" ]
    tags: [ 'v[0-9].[0-9]' ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:
    name: "Build image"
    runs-on: ubuntu-22.04

    steps:
    - name: Checkout
      uses: actions/checkout@v3
    - name: Set up QEMU
      uses: docker/setup-qemu-action@v3
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3
    - name: Login to container registry
      uses: docker/login-action@v3
      with:
        registry: ${{ secrets.CONTAINER_REGISTRY_ADDRESS }}
        username: ${{ secrets.CONTAINER_REGISTRY_USER }}
        password: ${{ secrets.CONTAINER_REGISTRY_PASSWORD }}
    - name: Build image
      uses: docker/build-push-action@v5
      if: ${{ github.ref_type != 'tag' }}
      with:
        file: CarpetPlanner/Dockerfile
        platforms: linux/arm64
    - name: Build and push image
      uses: docker/build-push-action@v5
      if: ${{ github.ref_type == 'tag' }}
      with:
        file: CarpetPlanner/Dockerfile
        platforms: linux/arm64
        push: true
        tags: ${{ secrets.CONTAINER_REGISTRY_ADDRESS}}/carpetplanner:${{ github.ref_name }}
